### ISSUE TITLE
multiple misspellings on teamspec/about

### ISSUE THREAD

**Issue by sjakiestan** [Gamepro5/Gamepro5.com#11]
on https://gamepro5.com/teamspec/about you:

- spelled "paid" as "payed"
- spelled "TTK" as "TKK"
- spelled "thought" as "though"
- could've used "knowledge" instead of "skills"
- spelled "had to spend" as "had to spent"

spelled X as Y means that X is correct, and Y is current.

**Comment by Gamepro5** [comment]
Thanks! I usually write these directly in-code, so auto correct doesn't come into play.
